---
title: "Perceptions of drinking water management and safety: A public survey of U.S. residents"
subtitle: "Supplementary Materials"
author:
  - name: Michael Schramm
    orcid: 0000-0003-1876-6592
    email: michael.schramm@ag.tamu.edu
    affiliations:
       - id: ag
         name: Texas A&M AgriLife
         department: Texas Water Resources Institute
         city: College Station, TX
         country: USA
  - name: Allen Berthold
    affiliations:
      -  ref: ag
  - name: Audrey McCrary
    orcid: 0000-0002-7061-6113
    affiliations:
      - ref: ag
  - name: Stephanie deVilleneuve
    orcid: 0009-0002-3984-035X
    affiliations:
      - ref: ag

format:
  hikmah-pdf:
    fontfamily: Roboto
    fontfamilyoptions: sfdefault
    include-in-header: 
      text: |
        \usepackage{pdflscape}
        \UseTblrLibrary{varwidth, counter}
        \renewcommand{\thetable}{S\arabic{table}}
  
keep-tex: true


knitr: 
  opts_chunk: 
    echo: false
    fig-width: 6
    fig-asp: 0.618
    out-width: "100%"
    fig-dpi: 300
    dev: "ragg_png"

---

```{r}
#| label: setup
#| echo: false
#| message: false


library(modelsummary)
library(ragg)
library(survey)
library(targets)
library(tidyverse)
library(tinytable)

font_hoist <- function(family, silent = FALSE) {
  font_specs <- systemfonts::system_fonts() |> 
    dplyr::filter(family == {{family}}) |> 
    dplyr::mutate(family = paste(family, style)) |> 
    dplyr::select(plain = path, name = family)
  
  purrr::pwalk(as.list(font_specs), systemfonts::register_font)
  
  if (!silent)  message(paste0("Hoisted ", nrow(font_specs), " variants:\n",
                               paste(font_specs$name, collapse = "\n")))
}

font_hoist("Manrope")

```



```{r}
#| results: asis

tibble(
  Questions = c(
    "What is the source of your household tap water?",
    "What is your main source of drinking water?",
    "Has your primary source of drinking water ever been impacted by any of the following issues? (select all that apply)",
    "On a scale from 0 to 10, how safe do you believe your drinking water is for consumption?",
    "\\textsuperscript{1}What is your level of trust in the following entities for making sure drinking water is safe for consumption:
    \\begin{itemize}[nosep]
    \\item Federal government
    \\item State government
    \\item Local government
    \\item Water utility
    \\item Landlords, property manager
    \\item Household residents
    \\end{itemize}",
    "\\textsuperscript{1}How often do you use the following sources to get information about drinking water quality?
    \\begin{itemize}[nosep]
    \\item Local news agency
    \\item National news agency
    \\item Local newspaper
    \\item National newspaper
    \\item Social media
    \\item Radio or podcast
    \\item Word of mouth
    \\item Email
    \\item Government agencies
    \\item My water provider
    \\item Other
    \\end{itemize}"),
  `Response Options` = c(
    "\\begin{itemize}[nosep]
    \\item[$\\square$] Public supply - municipal 
    \\item[$\\square$] Public supply - rural water district
    \\item[$\\square$] Private supply - private well, river, pond, lake
    \\item[$\\square$] Private supply - rainwater harvest system
    \\item[$\\square$] I don't know
    \\item[$\\square$] Other
    \\end{itemize}",
    "\\begin{itemize}[nosep]
    \\item[$\\square$] Unfiltered tap water
    \\item[$\\square$] Filtered tap water
    \\item[$\\square$] Bottled or prepackaged water
    \\item[$\\square$] Other
    \\end{itemize}",
    "\\begin{itemize}[nosep]
    \\item[$\\square$] Odd taste
    \\item[$\\square$] Odd smell
    \\item[$\\square$] Discolored water
    \\item[$\\square$] Cloudy water
    \\item[$\\square$] Staining of clothes, teeth, or skin
    \\item[$\\square$] Saltiness (high salt content)
    \\item[$\\square$] Hardness or scale buildup (high mineral content)
    \\item[$\\square$] Corrosion of pipes or water fixtures
    \\item[$\\square$] Boil water notice
    \\item[$\\square$] Water shortage
    \\item[$\\square$] None of the above
    \\item[$\\square$] Other
    \\end{itemize}",
    "Scale, 0-10",
    "\\begin{itemize}[nosep]
    \\item[$\\square$] Do not trust at all
    \\item[$\\square$] Somewhat trust
    \\item[$\\square$] Moderately trust
    \\item[$\\square$] Mostly trust
    \\item[$\\square$] Fully trust
    \\end{itemize}",
    "\\begin{itemize}[nosep]
    \\item[$\\square$] Never
    \\item[$\\square$] Occasionally
    \\item[$\\square$] Sometimes
    \\item[$\\square$] Often
    \\item[$\\square$] Always
    \\end{itemize}")
  ) |> 
  tt(notes = list("1" = "Matrix style question."),
     caption = "Survey questions.") |> 
  theme_tt("multipage") |>
  style_tt(tabularray_inner = "measure=vbox, stretch=-1, column{1}={wd=75mm}, column{2}={wd=70mm}, hline{3-7}={dashed}",
           tabularray_outer = "label=tblr:quest") |> 
  print("latex") |> 
  capture.output(type = "output") |> 
  paste(sep = "\n") |> 
  writeLines()
```





```{r}
#| results: asis

tar_read(weighted_demo_tbl) |>
  group_tt(i = list("Age" = 1,
                    "Education" = 8,
                    "Race/Ethnicity" = 16,
                    "Sex/Gender" = 19
  )) |>
  style_tt(i = c(1,9,18,22),
           bold = TRUE) |> 
  style_tt(tabularray_inner = "rulesep={0pt}, rowsep={0pt}, colsep = {.5em}, vspan={default}",
           tabularray_outer = "caption={Unweighted and weighted survey demographics.}, label=tblr:one") |> 
  theme_tt("multipage") |>
  #format_tt(escape = "latex") |> 
  print("latex") |> 
  capture.output(type = "output") |> 
  paste(sep = "\n") |> 
  ## remove the table environment created by tinytable
  (\(x) gsub(pattern = "\\\\*begin*\\{*table*\\}", 
            replacement = "", 
            x = x)) () |> 
  (\(x) gsub(pattern = "\\\\*end*\\{*table*\\}",
            replacement = "",
            x = x)) () |>
  writeLines()

```




{{< pagebreak >}}
\newgeometry{lmargin=1cm,rmargin=1cm}
\blandscape


```{r}
#| results: asis


df <- tar_read(m2_coefs)$df |> 
  mutate(estimate = paste0(round(estimate, 2), ", [", round(conf.low, 2), ", ", round(conf.high, 2), "]"),
         statistic = round(statistic, 2),
         p.value =  format.pval(p.value, digits = max(1, getOption("digits") - 6),
                                nsmall = 2)) |> 
  rename("Odds-Ratio, [95\\% CI]" = estimate,
         "t-statistic" = statistic,
         "p-value" = p.value)

df_1 <- df |> 
  filter(level == "Filtered tap water") |> 
  select("Variable" = var, `Odds-Ratio, [95\\% CI]`, `t-statistic`, `p-value`) 
  
df_2 <- df |> 
  filter(level == "Bottled water") |> 
  select(`Odds-Ratio, [95\\% CI]`, `t-statistic`, `p-value`) 

cbind(df_1, df_2) |> 
  tt(caption = "Results of multinomial logistic regression model for primary source of drinking water.  Odds-ratios are relative to unfiltered tap water. \\label{tblr:m2}") |> 
  group_tt(j = list("Filtered tap water" = 2:4,
                    "Bottled water" = 5:7),
           i = list("Sex/Gender" = 2,
                    "Age" = 4,
                    "Race/Ethnicity" = 9,
                    "Education" = 10,
                    "Home Ownership" = 16,
                    "Income" = 17,
                    "Primary tap water supply" = 22,
                    "Taste, odor, color issues" = 25)) |> 
  format_tt(j = 1, escape = "latex") |> 
  style_tt(tabularray_inner = "rulesep={0pt}, rowsep={0pt}, colsep = {.5em}, vspan={default}"
           ) |> 
  theme_tt("multipage") |> 
  print("latex") |> 
  capture.output(type = "output") |> 
  paste(sep = "\n") |> 
  writeLines()


```






\elandscape
\restoregeometry


{{< pagebreak >}}

\newgeometry{lmargin=1cm,rmargin=1cm}
\blandscape


```{r}
#| results: asis

m3_coef_rename <- function(x) {
  get_estimates(x, include_reference = TRUE) |> 
    slice(1:32) |> 
    pull(term) |> 
    str_replace_all(c("SEX" = "", 
                      "AGEP" = "",
                      "RACE2" = "",
                      "SCHL" = "",
                      "HOWNSHP" = "",
                      "INCOME" = "",
                      "Q5" = "",
                      "Q7" = ""))
}

 

modelsummary(models = list("Water safety rating"= tar_read(m3), "Trust in water utility" = tar_read(m1)),
             shape = term ~ model + statistic,
             estimate = c("Odds-Ratio, [95\\% CI]" = "{estimate} [{conf.low}, {conf.high}]"),
             statistic = c("t-stat" = "statistic",
                           "p-value" = "p.value"),
             exponentiate = TRUE,
             include_reference = TRUE,
             coef_omit = "\\|",
             coef_rename = m3_coef_rename(tar_read(m3)),
             gof_map = NA,
             output = "tinytable") |> 
  group_tt(i = list("Sex/Gender" = 1,
                "Age" = 4,
                "Race/Ethnicity" = 10,
                "Education" = 12,
                "Homeownership" = 19,
                "Income" = 21,
                "Primary tap water supply" = 27,
                "Taste, odor, color issues"= 31)) |> 
  format_tt(j = 1,
            escape = "latex") |> 
  theme_tt("multipage") |> 
  style_tt(tabularray_inner = "rulesep={0pt}, rowsep={0pt}, colsep = {.5em}, vspan={default}",
           tabularray_outer = "caption = {Results of proportional odds-models on (1) water safety rating and (2) trust in water utilities. Model coefficients are displayed as odds-ratios relative to the reference level for each variable.\\label{tblr:m13}}") |> 
  print("latex") |> 
  capture.output(type = "output") |> 
  paste(sep = "\n") |> 
  writeLines()

```



\elandscape
\restoregeometry